### ISSUE TITLE
navigationsSate.children conflicts with another child

### ISSUE THREAD

**Issue by grigio** [jlyman/RN-NavigationExperimental-Redux-Example#10]
Thanks for this Example, i noticed that if i tap on the buttons fast the app crashes

![screenshot_20160423-194857](https://cloud.githubusercontent.com/assets/8074/14763176/3a80d428-098e-11e6-8c99-1624936d579e.png)

**Comment by tmattacchione** [comment]
I ran into this issue as well.  Make sure that your app is PUSHing and POPing...For me, the issue was that the app would never POP and this creates a duplicate key warning like you see above.

**Comment by jlyman** [comment]
Yep, there is certainly more guard logic that could be written into the pushing/popping actions. In a full application these state changes would likely be more complicated and involved; you'll want to make those decisions on a per-app basis.

**Comment by jlyman** [comment]
Closing due to age, feel free to re-open if need be.
