### ISSUE TITLE
Animations of the cards are not working

### ISSUE THREAD

**Issue by chogarcia** [jlyman/RN-NavigationExperimental-Redux-Example#13]
The title header is fine but the animations of the cards are not working
Something I am missing?

Any help would be much appreciated.

**Comment by ryankask** [comment]
@cho-is I was having a similar issue earlier today so I'm not sure if this is it but are you passing a `style` prop to `NavigationCard`?

After reading through https://github.com/facebook/react-native/pull/6632, I am doing something like the following:

``` js
const cardStyles = [
  NavigationExperimental.Card.CardStackStyleInterpolator.forHorizontal(props),
  styles.card,
];

return (
  <NavigationExperimental.Card
    {...props}
    style={cardStyles}
  />
);
```

**Comment by chogarcia** [comment]
oh! you saved my day! thank you for the tip, that worked!
