### ISSUE TITLE
Any good implementation for Modals? 

### ISSUE THREAD

**Issue by chogarcia** [jlyman/RN-NavigationExperimental-Redux-Example#17]
I was wondering how would you approach Modals?

Any help would be much appreciated.

**Comment by jlyman** [comment]
@cho-is Check out #19 for an example that I just cooked up. It's fairly simplistic, but could be enhanced on a per-application basis.

The nice thing about maintaining the navigation state as a separate entity is that anything you decide you want to be modal will be, so long as you write it to respect your state as such. The other visual aspects of modals, such as the tendency to pop up from the bottom and differing headers, can also be configured on a per-app basis.

If #19 helps answer your question I'll go ahead and merge it into master.

**Comment by wsun** [comment]
@cho-is if you're looking for a modal that appears on top of the previous view, you could probably use Modal or a custom Animated View, and perhaps store a boolean in navigationState to govern whether it appears. This [blog post](http://browniefed.com/blog/react-native-easy-overlay-modal-with-navigator/) suggests a comparable approach with the old Navigator.

**Comment by chogarcia** [comment]
@jlyman sorry I was a few days away from a screen. Thank you very much for the PR, much appreciated. 
#19 looks like it is exactly what I was looking for, to work with `NavigationCard.CardStackStyleInterpolator.forVertical()` although I had some issues, the Card being rendered twice. 

I definitively will test you approach later today and get back to you. 

@wsun thank you for the link.

**Comment by chogarcia** [comment]
Pull down to close does not seem to be working if you do it from the top, but just if you do it on the left side.

**Comment by chogarcia** [comment]
I think that probably the answer would be on `NavigationCardStack`, this is the one that has `direction` prop. [Source](https://github.com/facebook/react-native/blob/14eb427a8061e0c904ace022535070150c6872d4/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js#L99).

```
class NavigationCardStack extends React.Component<DefaultProps, Props, void> {
  _renderScene : NavigationSceneRenderer;

  static propTypes = {
    direction: PropTypes.oneOf([Directions.HORIZONTAL, Directions.VERTICAL]),
    navigationState: NavigationPropTypes.navigationParentState.isRequired,
    onNavigate: NavigationPropTypes.SceneRenderer.onNavigate,
    renderOverlay: PropTypes.func,
    renderScene: PropTypes.func.isRequired,
  };

...
```

**Comment by jlyman** [comment]
I think there are definite areas for improvement with the example, but I don't want to build 100% of the functionality since we're just mostly trying to demo basic NavExp functionality in combo with Redux here. Real-world implementations would incorporate many of those things you suggested, but I'm going to go ahead and merge that PR in for now so that we have a basic example in place.
