### ISSUE TITLE
Card re-renders to next card before performing animation

### ISSUE THREAD

**Issue by jlyman** [jlyman/RN-NavigationExperimental-Redux-Example#2]
When pushing/popping in the current set up, React Native will actually re-render the card and start to animate it simultaneously. This makes it look like there are two identical cards on the screen, and the original card is lost. In other words, if navigating from Card A to Card B, upon action Card A is replaced with Card B, and the new Card B is also swiped in, resulting in two Card Bs on the screen at the same time.

Watch the demo GIF in README.md carefully to see it in action.

**Comment by ericvicenti** [comment]
I believe that this has been fixed in recent versions of NavigationAnimatedView. Can you repro on react-native master?

**Comment by jlyman** [comment]
I can give that a try. Is the best way to just clone the react-native repo and replace the contents of `node_modules/react-native` with the new files?

**Comment by ericvicenti** [comment]
The bug is actually in the example code and is visible in this redux example, but I fixed it in #3

**Comment by jlyman** [comment]
That makes sense, I hadn't previously understood what `NavigationCard` was doing under the hood with regards to having multiple scenes rendered and animating between them. Thanks!
