### ISSUE TITLE
Intergrating DrawerLayoutAndroid

### ISSUE THREAD

**Issue by cyprusglobe** [jlyman/RN-NavigationExperimental-Redux-Example#22]
Im wondering how one will go about using DrawerLayoutAndroid with this?

@jlyman @ericvicenti

**Comment by ericvicenti** [comment]
Unfortunately DrawerLayoutAndroid has an imperitive API where we call methods on it to change internal state rather than a declarative API where we simply update props. So this isn't a super easy thing to do right now

**Comment by CesarLanderos** [comment]
i made it work by setting the navigator as a child of DrawerLayout and passing the method to toggle the drawer to the app toolbar, it could even be a app global state state, listen with a componentWillReceiveProps or something and toggle with a dispatch, there are a lot of ways to do this i believe, the way i did it works just fine.
