### ISSUE TITLE
no active scene found

### ISSUE THREAD

**Issue by vshy108** [jlyman/RN-NavigationExperimental-Redux-Example#24]
When I click "Go to Home Page" in Third Screen, 
it triggered the mentioned error at the line 232 
`invariant(!!activeScene, 'no active scene found');`
of _RN-NavigationExperimental-Redux-Example/node_modules/react-native/Libraries/NavigationExperimental/NavigationTransitioner.js_

**Comment by wsun** [comment]
https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/issues/23

@jlyman maybe worth removing this button for now

**Comment by jlyman** [comment]
@wsun unfortunately you're probably right. Trying to get to this and to do a 0.29 update soon.

@vshy108 see https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/issues/23
