### ISSUE TITLE
Not working on Android?

### ISSUE THREAD

**Issue by morrigan** [jlyman/RN-NavigationExperimental-Redux-Example#27]
I haven't tested on iOS but I tried with Android 5.1.0 and 6.0.1 and they both crash immediately on start. I tried both 0.29 and master branch.

**Comment by jlyman** [comment]
Thanks @morrigan, had missed a step in the Android migration from version 0.29 (thought that `react-native upgrade` had done it all for me). Should be good to go now, I tested on my Nexus 5X/6.0.1.
