### ISSUE TITLE
how to Open Modal onPress TabBar.Item?

### ISSUE THREAD

**Issue by joypatel04** [jlyman/RN-NavigationExperimental-Redux-Example#28]
I have three tabs in my application i want to open a modal on Center tab which has 5 Actions with Cancel button at bottom!
How to handle this?
Modal has to open on front 
Thanks
@jlyman

**Comment by jlyman** [comment]
What part specifically are you having issues with? There's a lot of different ways one could go about this (and simplest might be something like an [ActionSheet](http://facebook.github.io/react-native/docs/actionsheetios.html)), but I wouldn't know which is appropriate for your particular application.

**Comment by joypatel04** [comment]
@jlyman I am implementing a application which is CardStack as well as Tab Based so we have Actions button in middle of TabBar so i want to open a modal kind of ActionSheet with logos and faded background so tab is open new View on each tab but some how i resolve that on Actions button that if user press Actions button don't switch to new view just stay at current View and just open a modal so for modal i am using https://github.com/remobile/react-native-action-sheet and i don't have a view on Actions Tab so it's open without Animated.View (FadeInView)

If i use normal modal it's open but View is not there so it's not render  anything outside of modal

**Comment by jlyman** [comment]
Sorry, I think the question is too far beyond the scope of the what we're trying to do here. You might want to check out https://github.com/nak1b/react-native-composite-navigation, which provides more insight into interacting with tabs and different cardstacks in NavExp, it might be very helpful for you.
