### ISSUE TITLE
Remount screen on replace route

### ISSUE THREAD

**Issue by terrysahaidak** [jlyman/RN-NavigationExperimental-Redux-Example#6]
I'm building [Gitter](https://gitter.im) client with RN. I've used legacy navigator + wrapper around it to have my navigation state in my redux store. Yesterday I found out ExperimentalNavigation is exactly what I want.

In my app when people navigate from room to another room, RoomScreen should replace with a new room and trigger the cDM, but it won't.

So, how can I remount route on replacing it with the exactly same route but with new data (like roomId etc)? With legacy navigator, it works as well.

You can check the navigator's code [here](https://github.com/terrysahaidak/GitterMobile/blob/better-navigation/app/modules/navigation.js) and Root container code [here](https://github.com/terrysahaidak/GitterMobile/blob/better-navigation/app/screens/index.js).

Thanks.

**Comment by jlyman** [comment]
From the looks of the transcript on #reactiflux I believe @ericvicenti answered your question, let me know if not. 

For others curious, here's an excerpt from that chat:

> **terrysahaidak - 3/21/2016 at 10:59 AM**
> Hey, @ericvicenti. How can I replace my route (with remounting) with new route with same key?
> 
> **ericvicenti - 3/21/2016 at 12:08 PM**
> @terrysahaidak, to re-mount you would need a new key, just like normal react components
> I took a look at your code, it sounds like you want to isolate the keys to make them unique and use a 'type' field in your state to determine which type of screen it is
> looks good otherwise!

**Comment by terrysahaidak** [comment]
Yeah, forget to write it here.

So, if we want to replace route, we need to have a unique key for that route. So the common way to do that -- all your routes should have unique key and name or id to identify which component navigator should render.
